apiVersion: v1
kind: Service
metadata:
  name: {{ include "ductstream.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ductstream.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.serviceAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "ductstream.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
