apiVersion: v2
name: monitoring
description: Monitoring stack for WALlaby - Jaeger, Prometheus, Grafana, OTel Collector
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: jaeger
    version: "3.4.1"
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled

  - name: prometheus
    version: "25.27.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  - name: grafana
    version: "8.5.2"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
